-- VHDL Entity PTR3_HVPS_lib.HVPS_tb.symbol
--
-- Created:
--          by - nort.Domain Users (NORT-XPS14)
--          at - 14:56:40 11/16/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1b (Build 2)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;



ENTITY HVPS_tb IS
   GENERIC( 
      N_CHANNELS : integer := 14;
      WORD_SIZE  : integer := 16
   );
-- Declarations

END HVPS_tb ;

--
-- VHDL Architecture PTR3_HVPS_lib.HVPS_tb.struct
--
-- Created:
--          by - nort.Domain Users (NORT-XPS14)
--          at - 10:37:15 11/18/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1b (Build 2)
--

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_arith.ALL;
LIBRARY PTR3_HVPS_lib;
USE PTR3_HVPS_lib.ALL;


ARCHITECTURE struct OF HVPS_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ExpAck  : std_ulogic;
   SIGNAL ExpAddr : std_logic_vector(15 DOWNTO 0);
   SIGNAL ExpRd   : std_ulogic;
   SIGNAL ExpWr   : std_ulogic;
   SIGNAL clk     : std_ulogic;
   SIGNAL rData   : std_logic_vector(15 DOWNTO 0);
   SIGNAL rst     : std_ulogic;
   SIGNAL scl     : std_logic;
   SIGNAL sda     : std_logic;
   SIGNAL wData   : std_logic_vector(15 DOWNTO 0);


   -- Component Declarations
   COMPONENT HVPS
   GENERIC (
      N_CHANNELS : integer := 14
   );
   PORT (
      ExpAddr : IN     std_logic_vector (15 DOWNTO 0);
      ExpRd   : IN     std_ulogic ;
      ExpWr   : IN     std_ulogic ;
      clk     : IN     std_ulogic ;
      rst     : IN     std_ulogic ;
      wData   : IN     std_logic_vector (15 DOWNTO 0);
      ExpAck  : OUT    std_ulogic ;
      rData   : OUT    std_logic_vector (15 DOWNTO 0);
      scl     : INOUT  std_logic ;
      sda     : INOUT  std_logic 
   );
   END COMPONENT;
   COMPONENT HVPS_tester
   PORT (
      ExpAck  : IN     std_ulogic ;
      rData   : IN     std_logic_vector (15 DOWNTO 0);
      ExpAddr : OUT    std_logic_vector (15 DOWNTO 0);
      ExpRd   : OUT    std_ulogic ;
      ExpWr   : OUT    std_ulogic ;
      clk     : OUT    std_ulogic ;
      rst     : OUT    std_ulogic ;
      wData   : OUT    std_logic_vector (15 DOWNTO 0);
      scl     : INOUT  std_logic ;
      sda     : INOUT  std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : HVPS USE ENTITY PTR3_HVPS_lib.HVPS;
   FOR ALL : HVPS_tester USE ENTITY PTR3_HVPS_lib.HVPS_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : HVPS
      GENERIC MAP (
         N_CHANNELS => 14
      )
      PORT MAP (
         ExpAddr => ExpAddr,
         ExpRd   => ExpRd,
         ExpWr   => ExpWr,
         clk     => clk,
         rst     => rst,
         wData   => wData,
         ExpAck  => ExpAck,
         rData   => rData,
         scl     => scl,
         sda     => sda
      );
   U_1 : HVPS_tester
      PORT MAP (
         ExpAck  => ExpAck,
         rData   => rData,
         ExpAddr => ExpAddr,
         ExpRd   => ExpRd,
         ExpWr   => ExpWr,
         clk     => clk,
         rst     => rst,
         wData   => wData,
         scl     => scl,
         sda     => sda
      );

END struct;
